export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
export const RESET_CURRENT_TURN = 'RESET_CURRENT_TURN';
export const SET_USER_CHOICE = 'SET_USER_CHOICE';
export const SET_COMPUTER_CHOICE = 'SET_COMPUTER_CHOICE';
export const INCREASE_USER_SCORE = 'INCREASE_USER_SCORE';
export const INCREASE_COMPUTER_SCORE = 'INCREASE_COMPUTER_SCORE';
export const SET_WINNER = 'SET_WINNER';
